<a href="https://colab.research.google.com/github/Haayes/Nauka-esmart/blob/main/001_010_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 1](#1)
* [Ćwiczenie 2](#2)
* [Ćwiczenie 3](#3)
* [Ćwiczenie 4](#4)
* [Ćwiczenie 5](#5)
* [Ćwiczenie 6](#6)
* [Ćwiczenie 7](#7)
* [Ćwiczenie 8](#8)
* [Ćwiczenie 9](#9)
* [Ćwiczenie 10](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A,B,C,D]):
  print(f'{name}:{np.all(array)}')

A:True
B:False
C:False
D:True


### <a name='2'></a> Ćwiczenie 2
Sprawdź czy wszystkie elementy tablic $A, B$ oraz $C$ zwracają wartość logiczną _True_ wzdłuż osi z indeksem 1.


```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```



__Wskazówka:__ Użyj funkcji _np.all()_ z parametrem _axis._

### <a name='1'></a> Ćwiczenie 1
Sprawdź czy wszystkie elementy tablic $A, B, C$ oraz $D$ zwracają wartość logiczną _True_.



```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```



__Wskazówka:__ Użyj funkcji _np.all()._

In [11]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list('ABCD'), [A,B,C,D]):
  print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


In [12]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

for name, array in zip(list('ABC'), [A,B,C]):
  print(f'{name}:{np.all(array, axis = 1)}')

 

A:[ True  True]
B:[ True False]
C:[False  True]


### <a name='3'></a> Ćwiczenie 3
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```


__Wskazówka:__ Użyj funkcji _np.any()._

In [20]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABCD'), [A,B,C,D]):
  print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABC'), [A,B,C]):
  print(f'{name}:{np.all(array, axis = 1)}')

False

### <a name='4'></a> Ćwiczenie 4
Sprawdź czy jakikolwiek element tablic $A, B, C$ oraz $D$ odpowiednio, zwraca wartość logiczną _True_ wzdłuż osi z indeksem 0.


```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```



__Wskazówka:__ Użyj funkcji _np.any()_ z parametrem _axis._

In [22]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list('ABC'), [A,B,C]):
  print(f'{name}:{np.all(array)}')

A:False
B:False
C:False


In [ ]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])


for name, array in zip(list('ABC'), [A,B,C,D]):
  print(f'{name}:{np.any(array)}')

A:False
B:True
C:True


### <a name='5'></a> Ćwiczenie 5
Sprawdź tablicę $A$ pod kątem braków danych (_np.nan_).


```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```


__Wskazówka:__ Użyj funkcji _np.isnan()_.

In [24]:

for name, array in zip(list('A'), [A]):
  print(f'{name}:{np.isnan(array)}')

A:[[False False False  True]
 [False  True False False]]


In [ ]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
for name, array in zip(list('A'), [A]):
  print(f'{name}:{np.isnan(array)}')

np.isnan(A)

A:[[False False False  True]
 [False  True False False]]


array([[False, False, False,  True],
       [False,  True, False, False]])

### <a name='6'></a> Ćwiczenie 6
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise) z ustalonym poziomem tolerancji. Użyj funkcji _np.allclose()_ z domyślnymi parametrami.
 


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```


In [ ]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.equal(A,B)

array([False, False,  True])

### <a name='7'></a> Ćwiczenie 7
Sprawdź, czy poniższe tablice $A$ oraz $B$ są równe pod względem elementów (element-wise). Użyj operatora porównania _==_.


```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 8
Sprawdź, dla których elementów (element-wise) poniższa tablica $A$ ma większe wartości niż tablica $B$.


```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```



In [ ]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

A > B

array([ True, False, False, False])

### <a name='9'></a> Ćwiczenie 9
Stwórz tablicę numpy wymiaru _4x4_ wypełnioną zerami. Ustal typ danych na _int_.

__Oczekiwany wynik:__


```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```



__Wskazówka:__ Użyj funkcji _np.zeros()_.

In [ ]:
np.zeros(shape=(4,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Ćwiczenie 10
Stwórz tablicę numpy wymiaru _10x10_ wypełnioną liczbą 255. Ustal typ danych na _float_.

__Oczekiwany wynik:__


```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```



__Wskazówka:__ Użyj funkcji _np.ones()_ lub _np.full()_.

In [ ]:
np.ones(shape= (10,10), dtype='float',) * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [ ]:
A = np.arange (start = -5, stop = 10, step = 0.5)


In [ ]:
print(A)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5]


In [ ]:
A = A.reshape(10,-1)
print(A)

[[-5.  -4.5 -4. ]
 [-3.5 -3.  -2.5]
 [-2.  -1.5 -1. ]
 [-0.5  0.   0.5]
 [ 1.   1.5  2. ]
 [ 2.5  3.   3.5]
 [ 4.   4.5  5. ]
 [ 5.5  6.   6.5]
 [ 7.   7.5  8. ]
 [ 8.5  9.   9.5]]
