<a href="https://colab.research.google.com/github/Haayes/Nauka-esmart/blob/main/041_050_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 41](#1)
* [Ćwiczenie 42](#2)
* [Ćwiczenie 43](#3)
* [Ćwiczenie 44](#4)
* [Ćwiczenie 45](#5)
* [Ćwiczenie 46](#6)
* [Ćwiczenie 47](#7)
* [Ćwiczenie 48](#8)
* [Ćwiczenie 49](#9)
* [Ćwiczenie 50](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.21.6'

### <a name='1'></a> Ćwiczenie 41
Podana jest poniższa tablica $A$ o kształcie (2, 3).


```
A = np.array([[4, 2, 1],
              [6, 4, 2]])
```



In [ ]:
a = np.arange(start = 1, stop = 10)

print(a)


[1 2 3 4 5 6 7 8 9]


In [ ]:
A = np.arange (start = -5, stop = 10, step = 0.5)
A = A.reshape(10,-1)
print(A)

[[-5.  -4.5 -4. ]
 [-3.5 -3.  -2.5]
 [-2.  -1.5 -1. ]
 [-0.5  0.   0.5]
 [ 1.   1.5  2. ]
 [ 2.5  3.   3.5]
 [ 4.   4.5  5. ]
 [ 5.5  6.   6.5]
 [ 7.   7.5  8. ]
 [ 8.5  9.   9.5]]


* Rozszerz tablicę $A$ o jeden wymiar (dodaj nowy wymiar na początku). Oczekiwany kształt wyjściowej tablicy: _(1, 2, 3)_.

__Wskazówka:__ Użyj funkcji _np.expand_dims()_.

In [ ]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
np.expand_dims(a, axis = 0)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

* Rozszerz tablicę $A$ o jeden wymiar (dodaj nowy wymiar na końcu). Oczekiwany kształt wyjściowej tablicy: _(2, 3, 1)_.

__Wskazówka:__ Użyj funkcji _np.expand_dims()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='2'></a> Ćwiczenie 42
Wygeneruj trójwymiarową tablicę o nazwie _image_ i kształcie _(200, 300, 3)_ wypełnioną wartościami losowymi od 0 do 255 włącznie i typie danych _np.uint8_.

In [ ]:
image = np.random.randint(low = 0, high = 256, size=(200, 300, 3), dtype = np.uint8)

print(image)

[[[ 41 115 118]
  [ 84 233 122]
  [  9 233 198]
  ...
  [ 37  99 209]
  [211 120 126]
  [ 59  79  35]]

 [[136 156 232]
  [107 217 177]
  [129 224  85]
  ...
  [132  46 214]
  [107 200 163]
  [121  45 198]]

 [[ 58  69 203]
  [ 20  13 211]
  [254 145  72]
  ...
  [  6 183 128]
  [159 139  20]
  [217 117  31]]

 ...

 [[178  96 176]
  [178 151  78]
  [175 147 177]
  ...
  [169 200  37]
  [  9 171  29]
  [145 143  28]]

 [[189 185 126]
  [ 59  76 205]
  [  9 136  25]
  ...
  [ 62  31 235]
  [104 133 186]
  [154  50 165]]

 [[157 209 251]
  [181 230  48]
  [ 21 223 136]
  ...
  [ 76  88 111]
  [211 188  36]
  [ 23 111 239]]]


Nastepnie uruchom poniższy blok kodu. W rezultacie uzyskasz podgląd na losowo wygenerowany kolorowy obraz.

In [ ]:
from google.colab.patches import cv2_imshow

cv2_imshow(image)

__Uwaga:__ Kolorowy obraz można zapisać jako trójwymiarowa tablica numpy o kształcie: (wysokość, szerokość, kanał).  
Np. kanał RGB: Red, Green, Blue. Kanał BGR: Blue, Green, Red.  
Mówiąc precyzyjniej kolorowy obraz zapisujemy jako trójwymiarowa tablica numpy o kształcie: (wysokość, szerokość, 3).

### <a name='3'></a> Ćwiczenie 43
Tablica _image_ z poprzedniego zadania jest kształtu _(200, 300, 3)_. Wykonaj polecenia:
* Rozszerz tablicę _image_ o jeden wymiar (dodaj nowy wymiar na początku). Oczekiwany kształt wyjściowej tablicy: _(1, 200, 300, 3)_.

__Wskazówka:__ Użyj funkcji _np.expand_dims()_.

In [5]:
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(image.shape)

image = np.expand_dims(image, axis = 0)
print(image)

(200, 300, 3)
[[[[ 81  84 180]
   [239 195  87]
   [ 10 247 246]
   ...
   [ 49 136  91]
   [136 192 105]
   [  4 122 161]]

  [[121 115 195]
   [ 18   3 184]
   [253 169 244]
   ...
   [ 92 136 206]
   [ 89  89 113]
   [184   1  81]]

  [[198 236  19]
   [210  50 104]
   [ 12  47 217]
   ...
   [205  24 154]
   [241 227 167]
   [208 134 145]]

  ...

  [[107   5  23]
   [ 15 113  49]
   [209 132 124]
   ...
   [ 49  68  35]
   [123 147 197]
   [180 102  30]]

  [[244  63 109]
   [ 54  81  48]
   [ 92  68  76]
   ...
   [ 73 229  71]
   [178 143 234]
   [179 104 208]]

  [[117 172 184]
   [234 161  27]
   [ 72 233 138]
   ...
   [207   8  28]
   [132 237  84]
   [ 90 122 210]]]]


* Rozszerz tablicę _image_ o jeden wymiar (dodaj nowy wymiar na końcu). Oczekiwany kształt wyjściowej tablicy: _(200, 300, 3, 1)_.

__Wskazówka:__ Użyj funkcji _np.expand_dims()_.

In [7]:
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(image.shape)


image = np.expand_dims(image, axis = -1)
print(image)

(200, 300, 3)
[[[[ 45]
   [ 73]
   [176]]

  [[ 35]
   [195]
   [ 98]]

  [[ 19]
   [ 85]
   [ 45]]

  ...

  [[139]
   [234]
   [203]]

  [[148]
   [ 59]
   [ 32]]

  [[194]
   [123]
   [106]]]


 [[[ 36]
   [ 57]
   [127]]

  [[109]
   [ 39]
   [ 75]]

  [[ 11]
   [ 16]
   [240]]

  ...

  [[196]
   [156]
   [200]]

  [[219]
   [120]
   [ 30]]

  [[ 63]
   [ 40]
   [145]]]


 [[[ 48]
   [ 33]
   [103]]

  [[184]
   [253]
   [ 11]]

  [[108]
   [173]
   [249]]

  ...

  [[122]
   [201]
   [110]]

  [[  9]
   [ 38]
   [ 90]]

  [[ 92]
   [ 41]
   [ 70]]]


 ...


 [[[183]
   [ 52]
   [227]]

  [[ 67]
   [205]
   [  3]]

  [[ 42]
   [217]
   [ 79]]

  ...

  [[152]
   [  7]
   [111]]

  [[159]
   [ 80]
   [ 15]]

  [[107]
   [200]
   [189]]]


 [[[ 95]
   [179]
   [187]]

  [[173]
   [188]
   [ 21]]

  [[254]
   [229]
   [143]]

  ...

  [[ 93]
   [ 39]
   [ 35]]

  [[126]
   [138]
   [110]]

  [[110]
   [206]
   [ 27]]]


 [[[  8]
   [ 38]
   [146]]

  [[ 51]
   [  2]
   [ 37]]

  [[ 8

### <a name='4'></a> Ćwiczenie 44
Podane są dwie losowo wygenerowane tablice _image1_ oraz _image2_. 


```
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
```

Każdą z tych tablic rozszerz dodając jeden wymiar na początku i następnie połącz tak otrzymane tablice w jedną o nazwie _images_. Oczekiwany kształt tablicy wynikowej: _(2, 200, 300, 3)_.

In [12]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image1 = np.expand_dims(image1, axis = 0)
image2 = np.expand_dims(image2, axis = 0)

image = np.append(image1, image2, axis = 0) 
image.shape

# tutaj wpisz rozwiązanie

(2, 200, 300, 3)

### <a name='5'></a> Ćwiczenie 45
Z tablicy _images_ z poprzedniego zadania wytnij dla __pierwszego__ obrazu dziesięć pierwszych wierszy i dziesięć pierwszych kolumn z kanału trzeciego (indeks 2).

### <a name='6'></a> Ćwiczenie 46
Z tablicy _images_ z Ćwiczenia 44 wytnij dla __drugiego__ obrazu sto pierwszych wierszy i sto pierwszych kolumn z kanału pierwszego (indeks 0) i wyświetl za pomocą funkcji _cv2_imshow_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 47
Poniżej wyświetlono podgląd na pierwszy obraz z tablicy _images_ z Ćwiczenia 44.

In [ ]:
cv2_imshow(images[0])

Dla obrazu pierwszego z tablicy _images_ przypisz dla pikseli z indeksem $[50:150, 100:200]$ wartość 0 i następnie wyświetl tak otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

Dla obrazu drugiego z tablicy _images_ przypisz dla pikseli z indeksem $[100:150, :150]$ wartość 255 i następnie wyświetl tak otrzymany obraz.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 48
Podana jest poniższa tablica $A$ o kształcie _(1, 2, 3)_. 


```
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
```

Usuń zbędny pierwszy wymiar i otrzymaj tablicę o kształcie _(2, 3)_.

__Wskazówka:__ Użyj funkcji _np.squeeze()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 49
Podana jest poniższa tablica $A$ o kształcie _(4, 1)_. 

```
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
```

Usuń zbędny pierwszy wymiar i otrzymaj tablicę o kształcie _(4,)_.

__Wskazówka:__ Użyj funkcji _np.squeeze()_.


In [ ]:
# tutaj wpisz rozwiązanie

### <a name='10'></a> Ćwiczenie 50
Z tablicy _images_ wycięto pierwszy obraz w poniższy sposób:

In [ ]:
image1 = images[:1]
image1.shape

Wykorzystując wiedzę z poprzednich ćwiczeń usuń zbędny pierwszy wymiar otrzymanej tablicy _image1_.

In [ ]:
# tutaj wpisz rozwiązanie