<a href="https://colab.research.google.com/github/Haayes/Nauka-esmart/blob/main/Data_Science_Bootcamp_w_j%C4%99zyku_Python_od_A_do_Z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
np.__version__

'1.21.6'

In [12]:
a = np.random.randint(low=10, high=101, size=10)


In [16]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
for item in A:
  print(item)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [21]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
A = np.arange (start = -5, stop = 10, step = 0.5)

In [24]:
A = A.reshape(10,-1)

In [25]:
A

array([[-5. , -4.5, -4. ],
       [-3.5, -3. , -2.5],
       [-2. , -1.5, -1. ],
       [-0.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5]])

In [29]:
for item in A:
  print(item)

[-5.  -4.5 -4. ]
[-3.5 -3.  -2.5]
[-2.  -1.5 -1. ]
[-0.5  0.   0.5]
[1.  1.5 2. ]
[2.5 3.  3.5]
[4.  4.5 5. ]
[5.5 6.  6.5]
[7.  7.5 8. ]
[8.5 9.  9.5]


In [30]:
np.bitwise_and(A> -5, A<5)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])