<a href="https://colab.research.google.com/github/Haayes/Nauka-esmart/blob/main/Data_Science_Bootcamp_w_j%C4%99zyku_Python_od_A_do_Z.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
a = np.random.randint(low=10, high=101, size=10)


In [ ]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for item in A:
  print(item)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A = np.arange (start = -5, stop = 10, step = 0.5)

In [ ]:
A = A.reshape(10,-1)

In [ ]:
A

array([[-5. , -4.5, -4. ],
       [-3.5, -3. , -2.5],
       [-2. , -1.5, -1. ],
       [-0.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5],
       [ 4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5],
       [ 7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5]])

In [ ]:
for item in A:
  print(item)

[-5.  -4.5 -4. ]
[-3.5 -3.  -2.5]
[-2.  -1.5 -1. ]
[-0.5  0.   0.5]
[1.  1.5 2. ]
[2.5 3.  3.5]
[4.  4.5 5. ]
[5.5 6.  6.5]
[7.  7.5 8. ]
[8.5 9.  9.5]


In [ ]:
np.bitwise_and(A> -5, A<5)

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
np.linalg.norm(v1)


4.123105625617661

In [ ]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [ ]:
Z =  np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [ ]:
Z.shape


(2, 1)

In [ ]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [ ]:
np.dot(X, Y)


array([[13,  9, -4],
       [ 6,  2, -1]])

In [5]:
A= np.array([[2,4],[-1,3]])

In [7]:
round(np.linalg.det(A))

10

In [9]:
A= np.array([[2,4],[-1,3]])
np.trace(A)

5

In [11]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [12]:
A

array([[ 2,  4],
       [-1,  3]])

In [13]:
B = np.linalg.inv(A)

In [14]:
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [17]:
np.set_printoptions(precision=4, suppress = True)
np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [19]:
A= np.array([[2, 4],[1, -1]])

In [20]:
A

array([[ 2,  4],
       [ 1, -1]])

In [21]:
B = np. array ([[10],[-1]])

In [23]:
B

array([[10],
       [-1]])

In [26]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

In [27]:
X

array([[1.],
       [2.]])